<a href="https://colab.research.google.com/github/nitkum41/Data-Science/blob/main/creating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow 2.x

UsageError: Line magic function `%tensorflow` not found.


In [ ]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [ ]:
list1 = [1,2,3,4]
tf_list1 = tf.convert_to_tensor(list1,dtype=tf.float32)

list2 = [[1,2,3,4]]
tf_list2 = tf.convert_to_tensor(list2,dtype=tf.float32)

In [ ]:
type(tf_list1)
print(tf_list1)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [ ]:
type(list2)
print(tf_list2)

tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [ ]:
import numpy as np
import pandas as pd

arr1 = np.array([[1,2],[3,4]])
tf_arr=tf.convert_to_tensor(arr1,dtype=tf.float32)
print(tf_arr)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
